spring.application.name=CourseMicroService
spring.config.import=optional:configserver:http://localhost:8888
course-service.id=202
course-service.cname=Programming
course-service.author=Shikha
spring.profiles.active=dev
spring.cloud.config.profile=qa
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
